FROM rust:1.96-slim
WORKDIR /tmp
ARG BUILDPLATFORM
ARG TARGETPLATFORM
RUN echo "host: $BUILDPLATFORM, target: $TARGETPLATFORM"

# base environment
RUN apt update && apt install -y build-essential g++-aarch64-linux-gnu libc6-dev-arm64-cross libssl-dev wget unzip
RUN wget -q -O ./protoc-35.1-linux-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v35.1/protoc-35.1-linux-x86_64.zip
RUN unzip ./protoc-35.1-linux-x86_64.zip -d ./protoc-35.1
RUN cp ./protoc-35.1/bin/protoc /usr/local/bin/protoc
RUN cp -R ./protoc-35.1/include /usr/local
RUN rustup target add aarch64-unknown-linux-gnu
RUN rustup toolchain install --force-non-host stable-aarch64-unknown-linux-gnu
RUN cargo install --locked cargo-chef
